# CMake generated Testfile for 
# Source directory: /home/quackdcs/micro-opcua/tests/unit
# Build directory: /home/quackdcs/micro-opcua/b_nano/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_address_space_callbacks]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_address_space_callbacks")
set_tests_properties([=[test_address_space_callbacks]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_address_space_string_limits]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_address_space_string_limits")
set_tests_properties([=[test_address_space_string_limits]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_address_space_validation]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_address_space_validation")
set_tests_properties([=[test_address_space_validation]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_address_space_values]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_address_space_values")
set_tests_properties([=[test_address_space_values]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_aggregate_full]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_aggregate_full")
set_tests_properties([=[test_aggregate_full]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_analog_item]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_analog_item")
set_tests_properties([=[test_analog_item]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_async_opcua_inventory]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_async_opcua_inventory")
set_tests_properties([=[test_async_opcua_inventory]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_audit_events]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_audit_events")
set_tests_properties([=[test_audit_events]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_base_server_behaviour]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_base_server_behaviour")
set_tests_properties([=[test_base_server_behaviour]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_binary_array_errors]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_binary_array_errors")
set_tests_properties([=[test_binary_array_errors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_binary_bytestring_errors]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_binary_bytestring_errors")
set_tests_properties([=[test_binary_bytestring_errors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_binary_extension_object]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_binary_extension_object")
set_tests_properties([=[test_binary_extension_object]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_binary_extension_object_errors]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_binary_extension_object_errors")
set_tests_properties([=[test_binary_extension_object_errors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_binary_nodeid]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_binary_nodeid")
set_tests_properties([=[test_binary_nodeid]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_binary_nodeid_errors]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_binary_nodeid_errors")
set_tests_properties([=[test_binary_nodeid_errors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_binary_primitives]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_binary_primitives")
set_tests_properties([=[test_binary_primitives]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_binary_string]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_binary_string")
set_tests_properties([=[test_binary_string]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_binary_string_errors]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_binary_string_errors")
set_tests_properties([=[test_binary_string_errors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_binary_variant_datavalue]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_binary_variant_datavalue")
set_tests_properties([=[test_binary_variant_datavalue]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_browse_limits]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_browse_limits")
set_tests_properties([=[test_browse_limits]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_browse_service]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_browse_service")
set_tests_properties([=[test_browse_service]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_build_config]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_build_config")
set_tests_properties([=[test_build_config]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_capacity_propagation]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_capacity_propagation")
set_tests_properties([=[test_capacity_propagation]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_complex_types]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_complex_types")
set_tests_properties([=[test_complex_types]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_conformance_docs]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_conformance_docs")
set_tests_properties([=[test_conformance_docs]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_connection_multiplex]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_connection_multiplex")
set_tests_properties([=[test_connection_multiplex]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_da_type_nodes]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_da_type_nodes")
set_tests_properties([=[test_da_type_nodes]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_diagnostics]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_diagnostics")
set_tests_properties([=[test_diagnostics]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_discovery_encode]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_discovery_encode")
set_tests_properties([=[test_discovery_encode]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_discovery_endpoint]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_discovery_endpoint")
set_tests_properties([=[test_discovery_endpoint]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_discovery_services]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_discovery_services")
set_tests_properties([=[test_discovery_services]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_dispatch_services]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_dispatch_services")
set_tests_properties([=[test_dispatch_services]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_dispatch_session_order]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_dispatch_session_order")
set_tests_properties([=[test_dispatch_session_order]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_dispatch_subscription]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_dispatch_subscription")
set_tests_properties([=[test_dispatch_subscription]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_eu_information]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_eu_information")
set_tests_properties([=[test_eu_information]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_event_filter_select]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_event_filter_select")
set_tests_properties([=[test_event_filter_select]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_event_filter_where]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_event_filter_where")
set_tests_properties([=[test_event_filter_where]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_event_notifier]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_event_notifier")
set_tests_properties([=[test_event_notifier]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_event_serializer]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_event_serializer")
set_tests_properties([=[test_event_serializer]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_get_endpoints_gate]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_get_endpoints_gate")
set_tests_properties([=[test_get_endpoints_gate]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_history_memstore]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_history_memstore")
set_tests_properties([=[test_history_memstore]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_jwt]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_jwt")
set_tests_properties([=[test_jwt]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_message_chunk]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_message_chunk")
set_tests_properties([=[test_message_chunk]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_message_chunk_errors]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_message_chunk_errors")
set_tests_properties([=[test_message_chunk_errors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_method_call]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_method_call")
set_tests_properties([=[test_method_call]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_method_call_arbitrary]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_method_call_arbitrary")
set_tests_properties([=[test_method_call_arbitrary]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_method_call_errors]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_method_call_errors")
set_tests_properties([=[test_method_call_errors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_monitored_index_range]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_monitored_index_range")
set_tests_properties([=[test_monitored_index_range]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_no_heap_lifecycle]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_no_heap_lifecycle")
set_tests_properties([=[test_no_heap_lifecycle]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_no_stale_project_name]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_no_stale_project_name")
set_tests_properties([=[test_no_stale_project_name]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_notification_encoding]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_notification_encoding")
set_tests_properties([=[test_notification_encoding]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_operation_limits]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_operation_limits")
set_tests_properties([=[test_operation_limits]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_percent_deadband]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_percent_deadband")
set_tests_properties([=[test_percent_deadband]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_platform_adapter_contract]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_platform_adapter_contract")
set_tests_properties([=[test_platform_adapter_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_profile_surface]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_profile_surface")
set_tests_properties([=[test_profile_surface]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_public_headers]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_public_headers")
set_tests_properties([=[test_public_headers]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_read_browsename_namespace]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_read_browsename_namespace")
set_tests_properties([=[test_read_browsename_namespace]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_read_service]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_read_service")
set_tests_properties([=[test_read_service]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_read_timestamps_to_return]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_read_timestamps_to_return")
set_tests_properties([=[test_read_timestamps_to_return]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_reverse_connect]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_reverse_connect")
set_tests_properties([=[test_reverse_connect]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_secure_channel]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_secure_channel")
set_tests_properties([=[test_secure_channel]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_security_identity_errors]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_security_identity_errors")
set_tests_properties([=[test_security_identity_errors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_security_policy]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_security_policy")
set_tests_properties([=[test_security_policy]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_server_address_space_config]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_server_address_space_config")
set_tests_properties([=[test_server_address_space_config]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_server_config]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_server_config")
set_tests_properties([=[test_server_config]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_server_status_value]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_server_status_value")
set_tests_properties([=[test_server_status_value]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_service_dispatch]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_service_dispatch")
set_tests_properties([=[test_service_dispatch]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_service_header]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_service_header")
set_tests_properties([=[test_service_header]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_service_message]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_service_message")
set_tests_properties([=[test_service_message]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_service_state_errors]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_service_state_errors")
set_tests_properties([=[test_service_state_errors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_session]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_session")
set_tests_properties([=[test_session]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_session_auth]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_session_auth")
set_tests_properties([=[test_session_auth]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_size_report]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_size_report")
set_tests_properties([=[test_size_report]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_status]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_status")
set_tests_properties([=[test_status]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_subscription_deadband]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_subscription_deadband")
set_tests_properties([=[test_subscription_deadband]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_subscription_publish]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_subscription_publish")
set_tests_properties([=[test_subscription_publish]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_subscriptions_capacity]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_subscriptions_capacity")
set_tests_properties([=[test_subscriptions_capacity]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_subscriptions_errors]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_subscriptions_errors")
set_tests_properties([=[test_subscriptions_errors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_tcp_connection]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_tcp_connection")
set_tests_properties([=[test_tcp_connection]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_time_sync]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_time_sync")
set_tests_properties([=[test_time_sync]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_traceability_docs]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_traceability_docs")
set_tests_properties([=[test_traceability_docs]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_transfer_subscriptions]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_transfer_subscriptions")
set_tests_properties([=[test_transfer_subscriptions]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_type_system]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_type_system")
set_tests_properties([=[test_type_system]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_uasc_framing]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_uasc_framing")
set_tests_properties([=[test_uasc_framing]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_user_token_decoder]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_user_token_decoder")
set_tests_properties([=[test_user_token_decoder]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_user_token_encrypted]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_user_token_encrypted")
set_tests_properties([=[test_user_token_encrypted]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_write_errors]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_write_errors")
set_tests_properties([=[test_write_errors]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_write_response]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_write_response")
set_tests_properties([=[test_write_response]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_write_value_gate]=] "/home/quackdcs/micro-opcua/b_nano/tests/unit/test_write_value_gate")
set_tests_properties([=[test_write_value_gate]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;22;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;140;add_unity_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
add_test([=[test_size_report_script]=] "bash" "/home/quackdcs/micro-opcua/scripts/measure_size.sh")
set_tests_properties([=[test_size_report_script]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;150;add_test;/home/quackdcs/micro-opcua/tests/unit/CMakeLists.txt;0;")
