; platform/arduino/platformio.ini
[env:micro_opcua_arduino]
platform = atmelavr
board = uno
framework = arduino
build_flags = 
    -I../../include
    -DMICRO_OPCUA_PLATFORM_ARDUINO
src_build_flags = 
    -I../../include
lib_extra_dirs = ../../src
