/* include/muc_opcua/opcua_ids.h */
#ifndef MUC_OPCUA_OPCUA_IDS_H
#define MUC_OPCUA_OPCUA_IDS_H

#include "muc_opcua/opcua_types.h"

#define MU_ID_FINDSERVERSREQUEST 422
#define MU_ID_FINDSERVERSRESPONSE 425
#define MU_ID_GETENDPOINTSREQUEST 428
#define MU_ID_GETENDPOINTSRESPONSE 431

#define MU_ID_OPENSECURECHANNELREQUEST 446
#define MU_ID_OPENSECURECHANNELRESPONSE 449
#define MU_ID_CLOSESECURECHANNELREQUEST 452
#define MU_ID_CLOSESECURECHANNELRESPONSE 455

#define MU_ID_CREATESESSIONREQUEST 461
#define MU_ID_CREATESESSIONRESPONSE 464
#define MU_ID_ACTIVATESESSIONREQUEST 467
#define MU_ID_ACTIVATESESSIONRESPONSE 470
#define MU_ID_CLOSESESSIONREQUEST 473
#define MU_ID_CLOSESESSIONRESPONSE 476

#define MU_ID_ADDNODESREQUEST 488
#define MU_ID_ADDNODESRESPONSE 491
#define MU_ID_ADDREFERENCESREQUEST 494
#define MU_ID_ADDREFERENCESRESPONSE 497
#define MU_ID_DELETENODESREQUEST 500
#define MU_ID_DELETENODESRESPONSE 503
#define MU_ID_DELETEREFERENCESREQUEST 506
#define MU_ID_DELETEREFERENCESRESPONSE 509

#define MU_ID_ANONYMOUSIDENTITYTOKEN_ENCODING_DEFAULTBINARY 321

#define MU_ID_SERVICEFAULT 397 /* ServiceFault_Encoding_DefaultBinary */

#define MU_ID_BROWSEREQUEST 527
#define MU_ID_BROWSERESPONSE 530
#define MU_ID_BROWSENEXTREQUEST 533
#define MU_ID_BROWSENEXTRESPONSE 536
#define MU_ID_TRANSLATEBROWSEPATHSTONODEIDSREQUEST 554
#define MU_ID_TRANSLATEBROWSEPATHSTONODEIDSRESPONSE 557
#define MU_ID_REGISTERNODESREQUEST 560
#define MU_ID_REGISTERNODESRESPONSE 563
#define MU_ID_UNREGISTERNODESREQUEST 566
#define MU_ID_UNREGISTERNODESRESPONSE 569

#define MU_ID_QUERYFIRSTREQUEST 615
#define MU_ID_QUERYFIRSTRESPONSE 618
#define MU_ID_QUERYNEXTREQUEST 621
#define MU_ID_QUERYNEXTRESPONSE 624

#define MU_ID_READREQUEST 631
#define MU_ID_READRESPONSE 634
#define MU_ID_HISTORYDATA_ENCODING_DEFAULTBINARY 658
#define MU_ID_READRAWMODIFIEDDETAILS_ENCODING_DEFAULTBINARY 649
#define MU_ID_UPDATEDATADETAILS_ENCODING_DEFAULTBINARY 682
#define MU_ID_DELETERAWMODIFIEDDETAILS_ENCODING_DEFAULTBINARY 688
#define MU_ID_HISTORYREADREQUEST 664
#define MU_ID_HISTORYREADRESPONSE 667
#define MU_ID_HISTORYUPDATEREQUEST 700
#define MU_ID_HISTORYUPDATERESPONSE 703
#define MU_ID_WRITEREQUEST 673
#define MU_ID_WRITERESPONSE 676
#define MU_ID_CALLREQUEST 712
#define MU_ID_CALLRESPONSE 715

#define MU_ID_CREATEMONITOREDITEMSREQUEST 751
#define MU_ID_CREATEMONITOREDITEMSRESPONSE 754
#define MU_ID_MODIFYMONITOREDITEMSREQUEST 763
#define MU_ID_MODIFYMONITOREDITEMSRESPONSE 766
#define MU_ID_SETMONITORINGMODEREQUEST 767
#define MU_ID_SETMONITORINGMODERESPONSE 770
#define MU_ID_SETTRIGGERINGREQUEST 773
#define MU_ID_SETTRIGGERINGRESPONSE 776
#define MU_ID_DELETEMONITOREDITEMSREQUEST 781
#define MU_ID_DELETEMONITOREDITEMSRESPONSE 784
#define MU_ID_CREATESUBSCRIPTIONREQUEST 787
#define MU_ID_CREATESUBSCRIPTIONRESPONSE 790
#define MU_ID_MODIFYSUBSCRIPTIONREQUEST 793
#define MU_ID_MODIFYSUBSCRIPTIONRESPONSE 796
#define MU_ID_SETPUBLISHINGMODEREQUEST 799
#define MU_ID_SETPUBLISHINGMODERESPONSE 802
#define MU_ID_PUBLISHREQUEST 826
#define MU_ID_PUBLISHRESPONSE 829
#define MU_ID_REPUBLISHREQUEST 832
#define MU_ID_REPUBLISHRESPONSE 835
#define MU_ID_DELETESUBSCRIPTIONSREQUEST 847
#define MU_ID_DELETESUBSCRIPTIONSRESPONSE 850

#define MU_ID_TRANSFERSUBSCRIPTIONSREQUEST 841
#define MU_ID_TRANSFERSUBSCRIPTIONSRESPONSE 844

#define MU_ID_AGGREGATEFILTER_ENCODING_DEFAULTBINARY 730
#define MU_ID_AGGREGATETYPE_AVERAGE 2342
#define MU_ID_AGGREGATETYPE_MINIMUM 2346
#define MU_ID_AGGREGATETYPE_MAXIMUM 2347

/* Additional OPC-10000-13 AggregateFunctionType IDs (MUC_OPCUA_AGGREGATE_FULL).
 * MaximumActualTime (2346) and MinimumActualTime (2347) are already
 * implemented as MU_ID_AGGREGATETYPE_MAXIMUM / _MINIMUM. */
#define MU_ID_AGGREGATETYPE_INTERPOLATIVE 2341
#define MU_ID_AGGREGATETYPE_TIME_AVERAGE 2343
#define MU_ID_AGGREGATETYPE_TOTAL 2344
#define MU_ID_AGGREGATETYPE_RANGE 2350
#define MU_ID_AGGREGATETYPE_COUNT 2351
#define MU_ID_AGGREGATETYPE_ANNOTATION_COUNT 2352
#define MU_ID_AGGREGATETYPE_END 2357
#define MU_ID_AGGREGATETYPE_START 2358
#define MU_ID_AGGREGATETYPE_DELTA 2359
#define MU_ID_AGGREGATETYPE_DURATION_GOOD 2360
#define MU_ID_AGGREGATETYPE_DURATION_BAD 2361
#define MU_ID_AGGREGATETYPE_DURATION_IN_STATE_ZERO 2363
#define MU_ID_AGGREGATETYPE_PERCENT_GOOD 2365
#define MU_ID_AGGREGATETYPE_PERCENT_BAD 2366
#define MU_ID_AGGREGATETYPE_WORST_QUALITY 2367
#define MU_ID_AGGREGATETYPE_TIME_AVERAGE_2 11286
#define MU_ID_AGGREGATETYPE_MAXIMUM_2 11287
#define MU_ID_AGGREGATETYPE_MINIMUM_2 11288
#define MU_ID_AGGREGATETYPE_WORST_QUALITY_2 11292
#define MU_ID_AGGREGATETYPE_TOTAL_2 11308
#define MU_ID_AGGREGATETYPE_DELTA_BOUNDS 11509

/* Data Access Server Facet — OPC-10000-3 §5.6.2 */
#define MU_ID_EURANGE 113                              /* EURange Property on AnalogItemType */
#define MU_ID_ENGINEERINGUNITS 115                     /* EngineeringUnits Property */
#define MU_ID_INSTRUMENTRANGE 117                      /* InstrumentRange Property */
#define MU_ID_ANALOGITEMTYPE 2368                      /* AnalogItemType ObjectType */
#define MU_ID_RANGE_ENCODING_DEFAULTBINARY 121         /* Range data type encoding */
#define MU_ID_EUINFORMATION_ENCODING_DEFAULTBINARY 125 /* EUInformation encoding */
#define MU_ID_PERCENTDEADBAND 3                        /* PercentDeadband type in DataChangeFilter */

#endif /* MUC_OPCUA_OPCUA_IDS_H */
