# CMake generated Testfile for 
# Source directory: /home/quackdcs/micro-opcua/tests/integration
# Build directory: /home/quackdcs/micro-opcua/b_push/tests/integration
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_minimal_server_flow]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_minimal_server_flow")
set_tests_properties([=[test_minimal_server_flow]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;5;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_discovery_endpoint_no_session]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_discovery_endpoint_no_session")
set_tests_properties([=[test_discovery_endpoint_no_session]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;9;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_single_client_limit]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_single_client_limit")
set_tests_properties([=[test_single_client_limit]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;13;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_server_handshake]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_server_handshake")
set_tests_properties([=[test_server_handshake]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;17;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_response_regression]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_response_regression")
set_tests_properties([=[test_response_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;21;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_server_framing]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_server_framing")
set_tests_properties([=[test_server_framing]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;25;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_server_handshake_secure]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_server_handshake_secure")
set_tests_properties([=[test_server_handshake_secure]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;30;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_connection_robustness]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_connection_robustness")
set_tests_properties([=[test_connection_robustness]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;35;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_view_services]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_view_services")
set_tests_properties([=[test_view_services]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;40;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_translate_browse_path_gate]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_translate_browse_path_gate")
set_tests_properties([=[test_translate_browse_path_gate]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;49;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_subscriptions]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_subscriptions")
set_tests_properties([=[test_subscriptions]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;55;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_user_auth_plaintext]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_user_auth_plaintext")
set_tests_properties([=[test_user_auth_plaintext]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;62;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_user_auth_encrypted]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_user_auth_encrypted")
set_tests_properties([=[test_user_auth_encrypted]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;71;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_user_auth_certificate]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_user_auth_certificate")
set_tests_properties([=[test_user_auth_certificate]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;83;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_user_auth_secure_e2e]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_user_auth_secure_e2e")
set_tests_properties([=[test_user_auth_secure_e2e]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;88;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_write_service_integration]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_write_service_integration")
set_tests_properties([=[test_write_service_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;95;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_secure_handshake_modern]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_secure_handshake_modern")
set_tests_properties([=[test_secure_handshake_modern]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;104;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_ecc_handshake_e2e]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_ecc_handshake_e2e")
set_tests_properties([=[test_ecc_handshake_e2e]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;113;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_event_notifications]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_event_notifications")
set_tests_properties([=[test_event_notifications]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;120;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
add_test([=[test_jwt_activate_session]=] "/home/quackdcs/micro-opcua/b_push/tests/integration/test_jwt_activate_session")
set_tests_properties([=[test_jwt_activate_session]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;131;add_test;/home/quackdcs/micro-opcua/tests/integration/CMakeLists.txt;0;")
