/* tests/unit/test_status.c */

#include "micro_opcua/status.h"
#include <unity.h>

void setUp(void) {}
void tearDown(void) {}

void test_status_values_match_opcua_common_statuscodes(void) {
    /* OPC-10000-4 §7.38.2 Common StatusCodes; numeric values from
       OPC Foundation UA NodeSet StatusCode.csv. */
    TEST_ASSERT_EQUAL_HEX32(0x00000000u, MU_STATUS_GOOD);
    TEST_ASSERT_EQUAL_HEX32(0x803E0000u, MU_STATUS_BAD_NOTFOUND);
    TEST_ASSERT_EQUAL_HEX32(0x805F0000u, MU_STATUS_BAD_NODECLASSINVALID);
    TEST_ASSERT_EQUAL_HEX32(0x805E0000u, MU_STATUS_BAD_NODEIDEXISTS);
    TEST_ASSERT_EQUAL_HEX32(0x805D0000u, MU_STATUS_BAD_NODEIDREJECTED);
    TEST_ASSERT_EQUAL_HEX32(0x804B0000u, MU_STATUS_BAD_NOCONTINUATIONPOINTS);
    TEST_ASSERT_EQUAL_HEX32(0x80430000u, MU_STATUS_BAD_MONITOREDITEMFILTERINVALID);
    TEST_ASSERT_EQUAL_HEX32(0x80440000u, MU_STATUS_BAD_MONITOREDITEMFILTERUNSUPPORTED);
    TEST_ASSERT_EQUAL_HEX32(0x80730000u, MU_STATUS_BAD_WRITENOTSUPPORTED);
    TEST_ASSERT_EQUAL_HEX32(0x80720000u, MU_STATUS_BAD_HISTORYOPERATIONUNSUPPORTED);
    TEST_ASSERT_EQUAL_HEX32(0x80770000u, MU_STATUS_BAD_TOOMANYSUBSCRIPTIONS);
#ifdef MU_STATUS_BAD_TOOMANYPUBLISHREQUESTS
    TEST_ASSERT_EQUAL_HEX32(0x80780000u, MU_STATUS_BAD_TOOMANYPUBLISHREQUESTS);
#endif
#ifdef MU_STATUS_BAD_SEQUENCENUMBERUNKNOWN
    TEST_ASSERT_EQUAL_HEX32(0x807A0000u, MU_STATUS_BAD_SEQUENCENUMBERUNKNOWN);
#endif
#ifdef MU_STATUS_BAD_MESSAGENOTAVAILABLE
    TEST_ASSERT_EQUAL_HEX32(0x807B0000u, MU_STATUS_BAD_MESSAGENOTAVAILABLE);
#endif
}

void test_status_values_for_certificate_aliases_do_not_collide_with_unrelated_codes(void) {
    /* The public user-certificate aliases map to certificate StatusCodes from
       OPC-10000-4 §7.38.2 instead of colliding with unrelated codes. */
    TEST_ASSERT_EQUAL_HEX32(0x80120000u, MU_STATUS_BAD_USERCERTIFICATEINVALID);
    TEST_ASSERT_EQUAL_HEX32(0x801A0000u, MU_STATUS_BAD_USERCERTIFICATEUNTRUSTED);
}

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_status_values_match_opcua_common_statuscodes);
    RUN_TEST(test_status_values_for_certificate_aliases_do_not_collide_with_unrelated_codes);
    return UNITY_END();
}
